version: '3.8'

services:
  twitter-analysis:
    build: .
    container_name: twitter-layoffs-analysis
    volumes:
      - ./output:/app/output
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    restart: unless-stopped